### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kamontat** [whs/grader#10]
```
[ERROR] InnoDB: Cannot allocate memory for the buffer pool
[ERROR] Plugin 'InnoDB' init function returned error.
[ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
[ERROR] Unknown/unsupported storage engine: InnoDB
```

<img width="940" alt="screen shot 2560-06-02 at 9 49 38 am" src="https://cloud.githubusercontent.com/assets/14089557/26709035/f81cd28c-4779-11e7-8543-ed38dca8e0ef.png">
<img width="1060" alt="screen shot 2560-06-02 at 9 47 45 am" src="https://cloud.githubusercontent.com/assets/14089557/26709036/f81df50e-4779-11e7-8820-97281f03caf2.png">

**Comment by kamontat** [comment]
Ohh, I already fixed it by add more swap memory space

**Comment by kamontat** [comment]
What is allow host and grader secret mean?

**Comment by kamontat** [comment]
Now I have new error:

```
Host 'xxx.xx.xxx.xxx' is not allowed to connect to this MySQL server
```

**Comment by whs** [comment]
ALLOWED_HOST is a list of allowed domain names. This is a security feature, see [Django docs](https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts).

Grader secret can be string that is set to the same in both grader backend and the runner. It is used by runner to authenticate with the grader backend. This string should be secret and unpredictable.

For your MySQL error, check your MySQL server configuration.

**Comment by kamontat** [comment]
Is mysql server run on docker, so how can i watch the configuration

**Comment by whs** [comment]
By default the mariadb/mariadb image shouldn't have host restriction for the users created by the startup script (root and one optional custom user). Did you try to add additional user or something?

**Comment by kamontat** [comment]
Nope,I just create new server with Linux 16.10 I think, and install git and docker
