### ISSUE TITLE
ImportError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by pchaow** [whs/grader#8]
web_1         | wait-for-it.sh: timeout occurred after waiting 15 seconds for mysql:3306
web_1         | [cont-init.d] 02-wait-db: exited 124.
web_1         | [cont-init.d] 03-migrate: executing... 
web_1         | Traceback (most recent call last):
web_1         |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 25, in <module>
web_1         |     import MySQLdb as Database
web_1         | ImportError: No module named 'MySQLdb'

**Comment by pchaow** [comment]
น่าจะเพิ่ม mysqlclient ลงใน requirement.txt ไหมครับ

**Comment by whs** [comment]
MySQL เป็น optional requirement เลยไม่อยู่ใน requirements.txt ครับ (ใช้ sqlite รันได้เหมือนกัน)

ในอิมเมจปกติผมจะ docker exec เข้าไป pip install mysqlclient อีกทีครับ
